# Generated by Django 4.2.6 on 2023-10-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trips', '0005_alter_trip_travel_mate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('travel_mate_name', models.CharField(max_length=30)),
                ('request_id', models.CharField(max_length=30, unique=True)),
                ('msg', models.TextField(null=True)),
                ('travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mate_trip_request', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_trip_request', to='Trips.trip', to_field='trip_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('travel_mate_name', models.CharField(max_length=30)),
                ('like_id', models.CharField(max_length=30, unique=True)),
                ('travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mate_trip_like', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_trip_like', to='Trips.trip', to_field='trip_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('travel_mate_name', models.CharField(max_length=30)),
                ('comment_id', models.CharField(max_length=30, unique=True)),
                ('comment', models.TextField(null=True)),
                ('travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mate_trip_comment', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_trip_comment', to='Trips.trip', to_field='trip_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
