# Generated by Django 4.2.6 on 2023-10-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
