# Generated by Django 4.2.3 on 2023-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0006_alter_follower_follower_alter_follower_travel_mate'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower_name',
            field=models.CharField(default='ww', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='travel_mate_name',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
