# Generated by Django 4.2.3 on 2023-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0009_triplike_travel_mate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='travel_mate_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tripcomment',
            name='travel_mate_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='triplike',
            name='travel_mate_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='travel_mate_profile',
            field=models.URLField(null=True),
        ),
    ]
