# Generated by Django 4.2.6 on 2023-12-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interactions', '0010_alter_follower_travel_mate_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('link', models.CharField(max_length=50, null=True)),
                ('travel_mate_name', models.CharField(max_length=30)),
                ('interacter_travel_mate_name', models.CharField(max_length=30)),
                ('interacter_travel_mate_profile', models.CharField(max_length=30)),
                ('interacter_travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactor', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
                ('travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
