# Generated by Django 4.2.6 on 2023-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0011_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactions',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
