# Generated by Django 4.2.6 on 2023-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interactions', '0012_interactions_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactions',
            name='interacter_travel_mate_profile',
            field=models.CharField(max_length=200),
        ),
    ]
