# Generated by Django 4.2.6 on 2023-10-25 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMate',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_mate_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('contry_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Your phone number appears to be invalid. Please double-check it', regex='\\d{10}')])),
                ('date_of_birth', models.DateField(null=True)),
                ('mother_tongue', models.CharField(choices=[('Mandarin Chinese', 'Mandarin Chinese'), ('Spanish', 'Spanish'), ('English', 'English'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Japanese', 'Japanese'), ('Punjabi', 'Punjabi'), ('German', 'German'), ('Javanese', 'Javanese'), ('Wu (Shanghainese)', 'Wu (Shanghainese)'), ('Telugu', 'Telugu'), ('Turkish', 'Turkish'), ('Korean', 'Korean'), ('French', 'French'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Urdu', 'Urdu')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='travelmates_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='travelmates_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
