# Generated by Django 4.2.6 on 2023-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmate',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
    ]
