# Generated by Django 4.2.6 on 2023-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0002_travelmate_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmate',
            name='fans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelmate',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelmate',
            name='trips',
            field=models.IntegerField(default=0),
        ),
    ]
