# Generated by Django 4.2.6 on 2023-10-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0003_travelmate_fans_travelmate_stars_travelmate_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelmate',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='travelmate',
            name='user_permissions',
        ),
    ]
