# Generated by Django 4.2.3 on 2023-11-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0004_remove_travelmate_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelmate',
            old_name='fans',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='travelmate',
            old_name='stars',
            new_name='followings',
        ),
    ]
