# Generated by Django 4.2.3 on 2023-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0005_rename_fans_travelmate_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmate',
            name='bio',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
