# Generated by Django 4.2.6 on 2023-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMates', '0007_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelmate',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
