# Generated by Django 4.2.6 on 2023-12-06 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.CharField(max_length=50, unique=True)),
                ('from_travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_from', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
                ('to_travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_to', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
                ('is_seen', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chats.conversation', to_field='conversation_id')),
                ('travel_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mate_messages', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
