# Generated by Django 4.2.6 on 2023-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0002_trip_travel_mate_trip_travel_mate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
