# Generated by Django 4.2.6 on 2023-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_mate_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
