# Generated by Django 4.2.6 on 2023-10-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trips', '0004_alter_trip_travel_mate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_mate_trips', to=settings.AUTH_USER_MODEL, to_field='travel_mate_id'),
        ),
    ]
