# Generated by Django 4.2.3 on 2023-10-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0005_alter_trip_travel_mate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='max_travel_mates',
            new_name='strength',
        ),
    ]
